import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Header from "~/components/header";
import { JotaiProvider } from "~/providers";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <JotaiProvider>
          <ThemeProvider
            defaultTheme="light"
            attribute="class"
            scriptProps={{
              "data-cfasync": "false",
            }}
          >
            <Toaster richColors position="top-center" visibleToasts={4} />
            <div className="h-full overflow-hidden">
              <Header />
              <main className="dash-layout-page-content-height scroll-bar-hidden overflow-y-scroll">
                {children}
              </main>
            </div>
          </ThemeProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
